"""phase2 group administration: holdings, ownerships, departments, company admin fields

Revision ID: 1b786167cd02
Revises: 55d2d244bc1b
Create Date: 2026-10-03 21:58:10.725686
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1b786167cd02'
down_revision: str | None = '55d2d244bc1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('legal_name_ar', sa.String(length=200), nullable=False),
    sa.Column('legal_name_en', sa.String(length=200), nullable=False),
    sa.Column('display_name_ar', sa.String(length=200), nullable=True),
    sa.Column('display_name_en', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('commercial_registration', sa.String(length=80), nullable=True),
    sa.Column('tax_number', sa.String(length=80), nullable=True),
    sa.Column('default_currency', sa.String(length=8), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holdings'))
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_holdings_status'), ['status'], unique=False)

    op.create_table('ownerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owned_company_id', sa.Integer(), nullable=False),
    sa.Column('owner_company_id', sa.Integer(), nullable=True),
    sa.Column('external_owner_name', sa.String(length=200), nullable=True),
    sa.Column('ownership_percentage', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owned_company_id'], ['companies.id'], name=op.f('fk_ownerships_owned_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_company_id'], ['companies.id'], name=op.f('fk_ownerships_owner_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ownerships')),
    sa.UniqueConstraint('owned_company_id', 'owner_company_id', 'external_owner_name', 'effective_from', name='uq_ownerships_stake_period')
    )
    with op.batch_alter_table('ownerships', schema=None) as batch_op:
        batch_op.create_index('ix_ownerships_owned', ['owned_company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ownerships_owned_company_id'), ['owned_company_id'], unique=False)
        batch_op.create_index('ix_ownerships_owner', ['owner_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ownerships_status'), ['status'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.String(length=180), nullable=False),
    sa.Column('name_en', sa.String(length=180), nullable=False),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('parent_department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_departments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name=op.f('fk_departments_manager_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], name=op.f('fk_departments_parent_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('company_id', 'code', name='uq_departments_company_code')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index('ix_departments_company', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_status'), ['status'], unique=False)

    # Existing rows predate these columns, so the two NOT NULL additions carry a
    # server_default. The default is kept afterwards: it is harmless and lets
    # future inserts that omit the field succeed on any driver.
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_name_ar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('legal_name_en', sa.String(length=200), nullable=True))
        batch_op.add_column(
            sa.Column(
                'company_type',
                sa.String(length=30),
                nullable=False,
                server_default='subsidiary',
            )
        )
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('commercial_registration', sa.String(length=80), nullable=True))
        batch_op.add_column(
            sa.Column(
                'currency', sa.String(length=8), nullable=False, server_default='SAR'
            )
        )
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_department', 'departments', ['department_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_department', type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('currency')
        batch_op.drop_column('commercial_registration')
        batch_op.drop_column('country')
        batch_op.drop_column('company_type')
        batch_op.drop_column('legal_name_en')
        batch_op.drop_column('legal_name_ar')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_status'))
        batch_op.drop_index(batch_op.f('ix_departments_company_id'))
        batch_op.drop_index('ix_departments_company')

    op.drop_table('departments')
    with op.batch_alter_table('ownerships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ownerships_status'))
        batch_op.drop_index('ix_ownerships_owner')
        batch_op.drop_index(batch_op.f('ix_ownerships_owned_company_id'))
        batch_op.drop_index('ix_ownerships_owned')

    op.drop_table('ownerships')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_status'))
        batch_op.drop_index(batch_op.f('ix_holdings_code'))

    op.drop_table('holdings')
    # ### end Alembic commands ###
