"""phase3 dynamic operations: forms, requirements, workflows, approvals, documents

Revision ID: 34f510488f9c
Revises: 1b786167cd02
Create Date: 2026-10-03 23:09:40.907413
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '34f510488f9c'
down_revision: str | None = '1b786167cd02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_categories'))
    )
    with op.batch_alter_table('document_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_categories_code'), ['code'], unique=True)

    op.create_table('dynamic_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dynamic_forms_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dynamic_forms'))
    )
    with op.batch_alter_table('dynamic_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamic_forms_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_forms_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_dynamic_forms_scope'), ['scope'], unique=False)
        batch_op.create_index('ix_dynamic_forms_scope_status', ['scope', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_forms_status'), ['status'], unique=False)

    op.create_table('form_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_form_companies_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['dynamic_forms.id'], name=op.f('fk_form_companies_form_id_dynamic_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_companies')),
    sa.UniqueConstraint('form_id', 'company_id', name='uq_form_companies_pair')
    )
    with op.batch_alter_table('form_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_companies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_companies_form_id'), ['form_id'], unique=False)

    op.create_table('form_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_form_versions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['dynamic_forms.id'], name=op.f('fk_form_versions_form_id_dynamic_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_versions')),
    sa.UniqueConstraint('form_id', 'version_number', name='uq_form_versions_number')
    )
    with op.batch_alter_table('form_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_versions_form_id'), ['form_id'], unique=False)
        batch_op.create_index('ix_form_versions_form_status', ['form_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_versions_status'), ['status'], unique=False)

    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allow_requirement_override', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_workflow_definitions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['dynamic_forms.id'], name=op.f('fk_workflow_definitions_form_id_dynamic_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definitions'))
    )
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_definitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_definitions_form_id'), ['form_id'], unique=False)
        batch_op.create_index('ix_workflow_definitions_form_status', ['form_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_definitions_status'), ['status'], unique=False)

    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('label_ar', sa.String(length=200), nullable=False),
    sa.Column('label_en', sa.String(length=200), nullable=False),
    sa.Column('placeholder_ar', sa.String(length=200), nullable=True),
    sa.Column('placeholder_en', sa.String(length=200), nullable=True),
    sa.Column('help_ar', sa.Text(), nullable=True),
    sa.Column('help_en', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], name=op.f('fk_form_fields_form_version_id_form_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_fields')),
    sa.UniqueConstraint('form_version_id', 'key', name='uq_form_fields_version_key')
    )
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_fields_form_version_id'), ['form_version_id'], unique=False)
        batch_op.create_index('ix_form_fields_version_order', ['form_version_id', 'display_order'], unique=False)

    op.create_table('form_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('requirement_type', sa.String(length=30), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], name=op.f('fk_form_requirements_form_version_id_form_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_requirements')),
    sa.UniqueConstraint('form_version_id', 'key', name='uq_form_requirements_version_key')
    )
    with op.batch_alter_table('form_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_requirements_form_version_id'), ['form_version_id'], unique=False)
        batch_op.create_index('ix_form_requirements_version_order', ['form_version_id', 'display_order'], unique=False)

    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_form_submissions_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_form_submissions_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['dynamic_forms.id'], name=op.f('fk_form_submissions_form_id_dynamic_forms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], name=op.f('fk_form_submissions_form_version_id_form_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_form_submissions_submitted_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_submissions'))
    )
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_submissions_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_form_submissions_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('ix_form_submissions_form', ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_form_version_id'), ['form_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_form_submissions_status'), ['status'], unique=False)
        batch_op.create_index('ix_form_submissions_submitter', ['submitted_by_id'], unique=False)

    op.create_table('workflow_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_workflow_versions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], name=op.f('fk_workflow_versions_definition_id_workflow_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_versions')),
    sa.UniqueConstraint('definition_id', 'version_number', name='uq_workflow_versions_number')
    )
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_versions_definition_id'), ['definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_versions_status'), ['status'], unique=False)

    op.create_table('submission_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('form_requirement_id', sa.Integer(), nullable=True),
    sa.Column('requirement_key', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('requirement_type', sa.String(length=30), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_satisfied', sa.Boolean(), nullable=False),
    sa.Column('satisfied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfied_by_id', sa.Integer(), nullable=True),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_requirement_id'], ['form_requirements.id'], name=op.f('fk_submission_requirements_form_requirement_id_form_requirements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['satisfied_by_id'], ['users.id'], name=op.f('fk_submission_requirements_satisfied_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], name=op.f('fk_submission_requirements_submission_id_form_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_requirements')),
    sa.UniqueConstraint('submission_id', 'requirement_key', name='uq_submission_requirements_key')
    )
    with op.batch_alter_table('submission_requirements', schema=None) as batch_op:
        batch_op.create_index('ix_submission_requirements_submission', ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_requirements_submission_id'), ['submission_id'], unique=False)

    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=30), nullable=False),
    sa.Column('assignment_config', sa.JSON(), nullable=True),
    sa.Column('required_permission', sa.String(length=80), nullable=True),
    sa.Column('allow_approve', sa.Boolean(), nullable=False),
    sa.Column('allow_reject', sa.Boolean(), nullable=False),
    sa.Column('allow_return', sa.Boolean(), nullable=False),
    sa.Column('require_comment_on_reject', sa.Boolean(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_workflow_steps_workflow_version_id_workflow_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps')),
    sa.UniqueConstraint('workflow_version_id', 'key', name='uq_workflow_steps_key')
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_steps_version_order', ['workflow_version_id', 'display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_steps_workflow_version_id'), ['workflow_version_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title_ar', sa.String(length=200), nullable=True),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=40), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('submission_requirement_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], name=op.f('fk_documents_category_id_document_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_documents_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], name=op.f('fk_documents_submission_id_form_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_requirement_id'], ['submission_requirements.id'], name=op.f('fk_documents_submission_requirement_id_submission_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name='uq_documents_storage_key')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_documents_category', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_documents_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('ix_documents_expiry', ['expiry_date'], unique=False)
        batch_op.create_index('ix_documents_related', ['related_entity_type', 'related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index('ix_documents_submission', ['submission_id'], unique=False)

    op.create_table('workflow_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('workflow_definition_id', sa.Integer(), nullable=False),
    sa.Column('workflow_version_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('current_step_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_workflow_instances_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_step_id'], ['workflow_steps.id'], name=op.f('fk_workflow_instances_current_step_id_workflow_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], name=op.f('fk_workflow_instances_submission_id_form_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], name=op.f('fk_workflow_instances_workflow_definition_id_workflow_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_workflow_instances_workflow_version_id_workflow_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_instances'))
    )
    with op.batch_alter_table('workflow_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_instances_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_status'), ['status'], unique=False)
        batch_op.create_index('ix_workflow_instances_submission', ['submission_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_submission_id'), ['submission_id'], unique=True)

    op.create_table('approval_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_approval_tasks_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], name=op.f('fk_approval_tasks_instance_id_workflow_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], name=op.f('fk_approval_tasks_step_id_workflow_steps'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_tasks'))
    )
    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index('ix_approval_tasks_assignee_status', ['assignee_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tasks_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index('ix_approval_tasks_instance_status', ['instance_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tasks_status'), ['status'], unique=False)

    op.create_table('approval_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_approval_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], name=op.f('fk_approval_events_instance_id_workflow_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], name=op.f('fk_approval_events_step_id_workflow_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], name=op.f('fk_approval_events_submission_id_form_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], name=op.f('fk_approval_events_task_id_approval_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_events'))
    )
    with op.batch_alter_table('approval_events', schema=None) as batch_op:
        batch_op.create_index('ix_approval_events_instance', ['instance_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_events_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_events_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###

    # Seed the baseline document categories (idempotent, additive only).
    _seed_categories()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_events_submission_id'))
        batch_op.drop_index(batch_op.f('ix_approval_events_instance_id'))
        batch_op.drop_index('ix_approval_events_instance')

    op.drop_table('approval_events')
    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_tasks_status'))
        batch_op.drop_index('ix_approval_tasks_instance_status')
        batch_op.drop_index(batch_op.f('ix_approval_tasks_instance_id'))
        batch_op.drop_index('ix_approval_tasks_assignee_status')
        batch_op.drop_index(batch_op.f('ix_approval_tasks_assignee_id'))

    op.drop_table('approval_tasks')
    with op.batch_alter_table('workflow_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_instances_submission_id'))
        batch_op.drop_index('ix_workflow_instances_submission')
        batch_op.drop_index(batch_op.f('ix_workflow_instances_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_instances_company_id'))

    op.drop_table('workflow_instances')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_submission')
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index('ix_documents_related')
        batch_op.drop_index('ix_documents_expiry')
        batch_op.drop_index('ix_documents_company_status')
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))
        batch_op.drop_index('ix_documents_category')

    op.drop_table('documents')
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_workflow_version_id'))
        batch_op.drop_index('ix_workflow_steps_version_order')

    op.drop_table('workflow_steps')
    with op.batch_alter_table('submission_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_requirements_submission_id'))
        batch_op.drop_index('ix_submission_requirements_submission')

    op.drop_table('submission_requirements')
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_versions_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_versions_definition_id'))

    op.drop_table('workflow_versions')
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_form_submissions_submitter')
        batch_op.drop_index(batch_op.f('ix_form_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_reference'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_form_version_id'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_form_id'))
        batch_op.drop_index('ix_form_submissions_form')
        batch_op.drop_index('ix_form_submissions_company_status')
        batch_op.drop_index(batch_op.f('ix_form_submissions_company_id'))

    op.drop_table('form_submissions')
    with op.batch_alter_table('form_requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_form_requirements_version_order')
        batch_op.drop_index(batch_op.f('ix_form_requirements_form_version_id'))

    op.drop_table('form_requirements')
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_index('ix_form_fields_version_order')
        batch_op.drop_index(batch_op.f('ix_form_fields_form_version_id'))

    op.drop_table('form_fields')
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_definitions_status'))
        batch_op.drop_index('ix_workflow_definitions_form_status')
        batch_op.drop_index(batch_op.f('ix_workflow_definitions_form_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_definitions_code'))

    op.drop_table('workflow_definitions')
    with op.batch_alter_table('form_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_versions_status'))
        batch_op.drop_index('ix_form_versions_form_status')
        batch_op.drop_index(batch_op.f('ix_form_versions_form_id'))

    op.drop_table('form_versions')
    with op.batch_alter_table('form_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_companies_form_id'))
        batch_op.drop_index(batch_op.f('ix_form_companies_company_id'))

    op.drop_table('form_companies')
    with op.batch_alter_table('dynamic_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamic_forms_status'))
        batch_op.drop_index('ix_dynamic_forms_scope_status')
        batch_op.drop_index(batch_op.f('ix_dynamic_forms_scope'))
        batch_op.drop_index(batch_op.f('ix_dynamic_forms_code'))
        batch_op.drop_index(batch_op.f('ix_dynamic_forms_category'))

    op.drop_table('dynamic_forms')
    with op.batch_alter_table('document_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_categories_code'))

    op.drop_table('document_categories')
    # ### end Alembic commands ###


# Baseline document categories, seeded by the migration so a fresh production
# database has them without running the demo seeder. Idempotent per code.
_BASELINE_CATEGORIES = [
    ("commercial_registration", "السجل التجاري", "Commercial Registration", 1),
    ("license", "رخصة", "License", 2),
    ("contract", "عقد", "Contract", 3),
    ("insurance", "تأمين", "Insurance", 4),
    ("employee_document", "مستند موظف", "Employee Document", 5),
    ("financial_document", "مستند مالي", "Financial Document", 6),
    ("legal_document", "مستند قانوني", "Legal Document", 7),
    ("quotation", "عرض سعر", "Quotation", 8),
    ("project_document", "مستند مشروع", "Project Document", 9),
    ("other", "أخرى", "Other", 10),
]


def _seed_categories() -> None:
    """Insert the baseline document categories (data-only, upgrade-safe)."""
    import datetime as _dt

    now = _dt.datetime.now(_dt.timezone.utc)
    categories = sa.table(
        "document_categories",
        sa.column("code", sa.String),
        sa.column("name_ar", sa.String),
        sa.column("name_en", sa.String),
        sa.column("display_order", sa.Integer),
        sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        categories,
        [
            {
                "code": code,
                "name_ar": name_ar,
                "name_en": name_en,
                "display_order": order,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            }
            for code, name_ar, name_en, order in _BASELINE_CATEGORIES
        ],
    )
