"""initial schema: identity, rbac, reports, support, ai, audit

Revision ID: 55d2d244bc1b
Revises: 
Create Date: 2026-10-02 03:59:56.006598
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '55d2d244bc1b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.String(length=180), nullable=False),
    sa.Column('name_en', sa.String(length=180), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_status'), ['status'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name_ar', sa.String(length=180), nullable=False),
    sa.Column('full_name_en', sa.String(length=180), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ai_conversations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_scope'), ['scope'], unique=False)
        batch_op.create_index('ix_ai_conversations_scope_company', ['scope', 'company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_time', ['actor_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_company', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_result', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('outstanding_receivables', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('important_developments', sa.Text(), nullable=True),
    sa.Column('new_customers', sa.Text(), nullable=True),
    sa.Column('new_opportunities', sa.Text(), nullable=True),
    sa.Column('major_problems', sa.Text(), nullable=True),
    sa.Column('support_required', sa.Text(), nullable=True),
    sa.Column('marketing_status', sa.Text(), nullable=True),
    sa.Column('business_development_status', sa.Text(), nullable=True),
    sa.Column('management_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_monthly_reports_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_monthly_reports_submitted_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_reports')),
    sa.UniqueConstraint('company_id', 'period_year', 'period_month', name='uq_report_company_period')
    )
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_reports_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_monthly_reports_company_period', ['company_id', 'period_year', 'period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_reports_status'), ['status'], unique=False)

    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_support_requests_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_support_requests_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_support_requests_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_requests'))
    )
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_requests_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_requests_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_requests_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_support_requests_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_requests_status'), ['status'], unique=False)

    op.create_table('user_company_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_user_company_access_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_company_access_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_company_access')),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company_access_pair')
    )
    with op.batch_alter_table('user_company_access', schema=None) as batch_op:
        batch_op.create_index('ix_user_company_access_company', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_company_access_user_id'), ['user_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_company_ids', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index('ix_ai_messages_conversation', ['conversation_id', 'id'], unique=False)

    op.create_table('monthly_report_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['monthly_reports.id'], name=op.f('fk_monthly_report_attachments_report_id_monthly_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_monthly_report_attachments_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_report_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_monthly_report_attachments_storage_key'))
    )
    with op.batch_alter_table('monthly_report_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_report_attachments_report_id'), ['report_id'], unique=False)

    op.create_table('monthly_report_financial_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('verified_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('verified_net_result', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('verified_outstanding_receivables', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('financial_notes', sa.Text(), nullable=True),
    sa.Column('is_financially_accurate', sa.Boolean(), nullable=True),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['monthly_reports.id'], name=op.f('fk_monthly_report_financial_reviews_report_id_monthly_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_monthly_report_financial_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_report_financial_reviews')),
    sa.UniqueConstraint('report_id', name='uq_financial_review_report')
    )
    with op.batch_alter_table('monthly_report_financial_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_report_financial_reviews_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_report_financial_reviews_status'), ['status'], unique=False)

    op.create_table('support_request_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['support_requests.id'], name=op.f('fk_support_request_attachments_request_id_support_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_support_request_attachments_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_request_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_support_request_attachments_storage_key'))
    )
    with op.batch_alter_table('support_request_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_request_attachments_request_id'), ['request_id'], unique=False)

    op.create_table('support_request_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_support_request_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['support_requests.id'], name=op.f('fk_support_request_comments_request_id_support_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_request_comments'))
    )
    with op.batch_alter_table('support_request_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_request_comments_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_request_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_request_comments_request_id'))

    op.drop_table('support_request_comments')
    with op.batch_alter_table('support_request_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_request_attachments_request_id'))

    op.drop_table('support_request_attachments')
    with op.batch_alter_table('monthly_report_financial_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_report_financial_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_monthly_report_financial_reviews_report_id'))

    op.drop_table('monthly_report_financial_reviews')
    with op.batch_alter_table('monthly_report_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_report_attachments_report_id'))

    op.drop_table('monthly_report_attachments')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_messages_conversation')

    op.drop_table('ai_messages')
    with op.batch_alter_table('user_company_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_company_access_user_id'))
        batch_op.drop_index('ix_user_company_access_company')

    op.drop_table('user_company_access')
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_requests_status'))
        batch_op.drop_index('ix_support_requests_company_status')
        batch_op.drop_index(batch_op.f('ix_support_requests_company_id'))
        batch_op.drop_index(batch_op.f('ix_support_requests_category'))
        batch_op.drop_index(batch_op.f('ix_support_requests_assigned_to_id'))

    op.drop_table('support_requests')
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_reports_status'))
        batch_op.drop_index('ix_monthly_reports_company_period')
        batch_op.drop_index(batch_op.f('ix_monthly_reports_company_id'))

    op.drop_table('monthly_reports')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_company')
        batch_op.drop_index('ix_audit_logs_actor_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))
        batch_op.drop_index('ix_ai_conversations_scope_company')
        batch_op.drop_index(batch_op.f('ix_ai_conversations_scope'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_company_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_code'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_status'))
        batch_op.drop_index(batch_op.f('ix_companies_code'))

    op.drop_table('companies')
    # ### end Alembic commands ###
