"""phase 10 public website leads and opportunities

Revision ID: 9615c678609f
Revises: 5ff680970d75
Create Date: 2026-10-04 05:15:21.002570
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9615c678609f'
down_revision: str | None = '5ff680970d75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('service_type', sa.String(length=40), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=120), nullable=True),
    sa.Column('utm_medium', sa.String(length=120), nullable=True),
    sa.Column('utm_campaign', sa.String(length=160), nullable=True),
    sa.Column('utm_content', sa.String(length=160), nullable=True),
    sa.Column('utm_term', sa.String(length=160), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('landing_page', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('routed_team', sa.String(length=60), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('routed_company_id', sa.Integer(), nullable=True),
    sa.Column('final_result', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_website_leads_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routed_company_id'], ['companies.id'], name=op.f('fk_website_leads_routed_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_leads')),
    sa.UniqueConstraint('reference', name='uq_website_leads_reference')
    )
    with op.batch_alter_table('website_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_leads_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_leads_market'), ['market'], unique=False)
        batch_op.create_index('ix_website_leads_market_service', ['market', 'service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_leads_routed_company_id'), ['routed_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_leads_routed_team'), ['routed_team'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_leads_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_leads_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_leads_status'), ['status'], unique=False)
        batch_op.create_index('ix_website_leads_status_created', ['status', 'created_at'], unique=False)

    op.create_table('website_lead_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['website_leads.id'], name=op.f('fk_website_lead_attachments_lead_id_website_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_lead_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_website_lead_attachments_storage_key'))
    )
    with op.batch_alter_table('website_lead_attachments', schema=None) as batch_op:
        batch_op.create_index('ix_website_lead_attachments_lead', ['lead_id'], unique=False)

    op.create_table('website_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('applicant_capacity', sa.String(length=30), nullable=False),
    sa.Column('opportunity_type', sa.String(length=30), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('business_age_years', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('reason_for_listing', sa.Text(), nullable=True),
    sa.Column('desired_outcome', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('public_title_ar', sa.String(length=200), nullable=True),
    sa.Column('public_title_en', sa.String(length=200), nullable=True),
    sa.Column('public_summary_ar', sa.Text(), nullable=True),
    sa.Column('public_summary_en', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['website_leads.id'], name=op.f('fk_website_opportunities_lead_id_website_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_website_opportunities_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_opportunities'))
    )
    with op.batch_alter_table('website_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_opportunities_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_opportunities_market'), ['market'], unique=False)
        batch_op.create_index('ix_website_opportunities_market_status', ['market', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_opportunities_opportunity_type'), ['opportunity_type'], unique=False)
        batch_op.create_index('ix_website_opportunities_public', ['is_public', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_opportunities_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_opportunities_status'))
        batch_op.drop_index('ix_website_opportunities_public')
        batch_op.drop_index(batch_op.f('ix_website_opportunities_opportunity_type'))
        batch_op.drop_index('ix_website_opportunities_market_status')
        batch_op.drop_index(batch_op.f('ix_website_opportunities_market'))
        batch_op.drop_index(batch_op.f('ix_website_opportunities_lead_id'))

    op.drop_table('website_opportunities')
    with op.batch_alter_table('website_lead_attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_website_lead_attachments_lead')

    op.drop_table('website_lead_attachments')
    with op.batch_alter_table('website_leads', schema=None) as batch_op:
        batch_op.drop_index('ix_website_leads_status_created')
        batch_op.drop_index(batch_op.f('ix_website_leads_status'))
        batch_op.drop_index(batch_op.f('ix_website_leads_source'))
        batch_op.drop_index(batch_op.f('ix_website_leads_service_type'))
        batch_op.drop_index(batch_op.f('ix_website_leads_routed_team'))
        batch_op.drop_index(batch_op.f('ix_website_leads_routed_company_id'))
        batch_op.drop_index('ix_website_leads_market_service')
        batch_op.drop_index(batch_op.f('ix_website_leads_market'))
        batch_op.drop_index(batch_op.f('ix_website_leads_email'))
        batch_op.drop_index(batch_op.f('ix_website_leads_assigned_to_id'))

    op.drop_table('website_leads')
    # ### end Alembic commands ###
