"""branding logo on holding

Revision ID: b7f1a7747880
Revises: 9615c678609f
Create Date: 2026-10-04 16:33:47.225851
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b7f1a7747880'
down_revision: str | None = '9615c678609f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_storage_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('logo_content_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('logo_original_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_column('logo_updated_at')
        batch_op.drop_column('logo_original_name')
        batch_op.drop_column('logo_content_type')
        batch_op.drop_column('logo_storage_key')

    # ### end Alembic commands ###
